### ISSUE TITLE
wrong emitted height in components with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by capc0** [chrum/ngx-autosize#57]
If this plugin is used within components that have the OnPush change detection strategy, the initial height is incorrect.

My guess is that the height of the clone (https://github.com/chrum/ngx-autosize/blob/master/projects/autosize/src/lib/autosize.directive.ts#L148) is not correct.
A possible fix could be to run https://angular.io/api/core/ChangeDetectorRef#detectChanges or wrap the code in a setTimeout.

**Comment by chrum** [comment]
sweet :) i just reproduced it, great finding!

**Comment by chrum** [comment]
hey @capc0 

Its a bit difficult to crack the problem. I noticed that its not really the thing with onPush strategy but with textarea packed in a component that receives value through inputs... its also problematic when textarea gets autosized immediately after app starts... 

...anyway :) i fixed what i was able to reproduce (all described above) so check 'next' channel please:
`npm install ngx-autosize@next`

if this doesnt help then can you do me a favor and put some example repo with the bug?

**Comment by capc0** [comment]
hi thanks for your feedback.
unfortunately the @next version did not fix the problem for me.
I will try to provide you a example repo within the next few days :)

**Comment by capc0** [comment]
Issue is reproducable here: https://stackblitz.com/edit/angular-jxkwwz?file=src/app/textarea-input/textarea-input.component.html

If you load the page, it shows 5 lines


![image](https://user-images.githubusercontent.com/27284008/90642386-97b9cd80-e232-11ea-94cc-94aea60c4ff1.png)

Clicking inside the textarea and then somewhere else in the document again increases the height

![image](https://user-images.githubusercontent.com/27284008/90642369-91c3ec80-e232-11ea-8fac-efaba317b4bb.png)

But it seems to be related to bootstrap, since If I remove the imports in the ```index.html``` it looks OK.

**Comment by gilsdav** [comment]
Same issue :)
Didn't get initial height. Need to focus in field to have correct size.
More information:
This occur mainly when field is hidden when page is loaded. I receive onResize event with value "NaN".
Here is my workaround:
![image](https://user-images.githubusercontent.com/21348530/108258026-e0a9fa80-715f-11eb-9d40-7b88550b65cc.png)

**Comment by sarahmarciano1** [comment]
Hi,
I am facing the same issue
any updates on this?
